theme: jekyll-theme-slate
title: Fethi Kahvecioğlu's Progress Journal
description: This journal is established for IE 423 course within Boğaziçi University Industrial Engineering Department in Fall 2023 term.
